version: '3.8'

services:
  flask_app:
    build: .
    container_name: company_database
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    env_file:
      - .env
    command: gunicorn --bind 0.0.0.0:5000 app:app